### ISSUE TITLE
python-pew package is just called "pew"

### ISSUE THREAD

**Issue by jamespo** [junaruga/fedora-pipenv#1]
for python 3 in FC27

Installation otherwise gives:

"nothing provides python-pew >= 0.1.26 "

So dependency needs to be fixed?

**Comment by junaruga** [comment]
Oh this repository is not official repository of Fedora pipenv spec file.
I guess right now no pipenv RPM in Fedora.
https://src.fedoraproject.org/

Feel free to fork and modify it.
It's public domain. You do not have to remain my name. You can modify everything.

**Comment by junaruga** [comment]
I found a person forked my repo. You may be able to do something with this person.
https://github.com/llunved/fedora-pipenv

**Comment by jamespo** [comment]
thanks

**Comment by junaruga** [comment]
@jamespo it looks pipenv is not officially on Fedora.
https://src.fedoraproject.org/rpms/pipenv

**Comment by junaruga** [comment]
Ref: https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/HJPSR4AUMJGKLST22YYU3FGMQPHMSKQM/

**Comment by jamespo** [comment]
Great. Thank you.
